/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CustomTemplate {
  'id' : string,
  'created' : Time,
  'name' : string,
  'canvasState' : string,
  'category' : TemplateCategory,
}
export interface PrebuiltTemplate {
  'id' : string,
  'name' : string,
  'description' : string,
  'thumbnailHint' : string,
  'category' : TemplateCategory,
}
export type TemplateCategory = { 'instagram' : null } |
  { 'old_money' : null };
export type Time = bigint;
export interface _SERVICE {
  'deleteCustomTemplate' : ActorMethod<[string], undefined>,
  'getAllCustomTemplates' : ActorMethod<[], Array<CustomTemplate>>,
  'getCustomTemplate' : ActorMethod<[string], CustomTemplate>,
  'getPrebuiltTemplates' : ActorMethod<[], Array<PrebuiltTemplate>>,
  'getTemplatesByCategory' : ActorMethod<
    [TemplateCategory],
    {
      'customTemplates' : Array<CustomTemplate>,
      'prebuiltTemplates' : Array<PrebuiltTemplate>,
    }
  >,
  'saveCustomTemplate' : ActorMethod<[CustomTemplate], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];