/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const TemplateCategory = IDL.Variant({
  'instagram' : IDL.Null,
  'old_money' : IDL.Null,
});
export const CustomTemplate = IDL.Record({
  'id' : IDL.Text,
  'created' : Time,
  'name' : IDL.Text,
  'canvasState' : IDL.Text,
  'category' : TemplateCategory,
});
export const PrebuiltTemplate = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'thumbnailHint' : IDL.Text,
  'category' : TemplateCategory,
});

export const idlService = IDL.Service({
  'deleteCustomTemplate' : IDL.Func([IDL.Text], [], []),
  'getAllCustomTemplates' : IDL.Func([], [IDL.Vec(CustomTemplate)], ['query']),
  'getCustomTemplate' : IDL.Func([IDL.Text], [CustomTemplate], ['query']),
  'getPrebuiltTemplates' : IDL.Func([], [IDL.Vec(PrebuiltTemplate)], ['query']),
  'getTemplatesByCategory' : IDL.Func(
      [TemplateCategory],
      [
        IDL.Record({
          'customTemplates' : IDL.Vec(CustomTemplate),
          'prebuiltTemplates' : IDL.Vec(PrebuiltTemplate),
        }),
      ],
      ['query'],
    ),
  'saveCustomTemplate' : IDL.Func([CustomTemplate], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const TemplateCategory = IDL.Variant({
    'instagram' : IDL.Null,
    'old_money' : IDL.Null,
  });
  const CustomTemplate = IDL.Record({
    'id' : IDL.Text,
    'created' : Time,
    'name' : IDL.Text,
    'canvasState' : IDL.Text,
    'category' : TemplateCategory,
  });
  const PrebuiltTemplate = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'thumbnailHint' : IDL.Text,
    'category' : TemplateCategory,
  });
  
  return IDL.Service({
    'deleteCustomTemplate' : IDL.Func([IDL.Text], [], []),
    'getAllCustomTemplates' : IDL.Func(
        [],
        [IDL.Vec(CustomTemplate)],
        ['query'],
      ),
    'getCustomTemplate' : IDL.Func([IDL.Text], [CustomTemplate], ['query']),
    'getPrebuiltTemplates' : IDL.Func(
        [],
        [IDL.Vec(PrebuiltTemplate)],
        ['query'],
      ),
    'getTemplatesByCategory' : IDL.Func(
        [TemplateCategory],
        [
          IDL.Record({
            'customTemplates' : IDL.Vec(CustomTemplate),
            'prebuiltTemplates' : IDL.Vec(PrebuiltTemplate),
          }),
        ],
        ['query'],
      ),
    'saveCustomTemplate' : IDL.Func([CustomTemplate], [], []),
  });
};

export const init = ({ IDL }) => { return []; };