/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CustomTemplate {
    id: string;
    created: Time;
    name: string;
    canvasState: string;
    category: TemplateCategory;
}
export type Time = bigint;
export interface PrebuiltTemplate {
    id: string;
    name: string;
    description: string;
    thumbnailHint: string;
    category: TemplateCategory;
}
export enum TemplateCategory {
    instagram = "instagram",
    old_money = "old_money"
}
export interface backendInterface {
    deleteCustomTemplate(id: string): Promise<void>;
    getAllCustomTemplates(): Promise<Array<CustomTemplate>>;
    getCustomTemplate(id: string): Promise<CustomTemplate>;
    getPrebuiltTemplates(): Promise<Array<PrebuiltTemplate>>;
    getTemplatesByCategory(category: TemplateCategory): Promise<{
        customTemplates: Array<CustomTemplate>;
        prebuiltTemplates: Array<PrebuiltTemplate>;
    }>;
    saveCustomTemplate(template: CustomTemplate): Promise<void>;
}
import type { CustomTemplate as _CustomTemplate, PrebuiltTemplate as _PrebuiltTemplate, TemplateCategory as _TemplateCategory, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async deleteCustomTemplate(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCustomTemplate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCustomTemplate(arg0);
            return result;
        }
    }
    async getAllCustomTemplates(): Promise<Array<CustomTemplate>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCustomTemplates();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCustomTemplates();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomTemplate(arg0: string): Promise<CustomTemplate> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomTemplate(arg0);
                return from_candid_CustomTemplate_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomTemplate(arg0);
            return from_candid_CustomTemplate_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPrebuiltTemplates(): Promise<Array<PrebuiltTemplate>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPrebuiltTemplates();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPrebuiltTemplates();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTemplatesByCategory(arg0: TemplateCategory): Promise<{
        customTemplates: Array<CustomTemplate>;
        prebuiltTemplates: Array<PrebuiltTemplate>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getTemplatesByCategory(to_candid_TemplateCategory_n9(this._uploadFile, this._downloadFile, arg0));
                return from_candid_record_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTemplatesByCategory(to_candid_TemplateCategory_n9(this._uploadFile, this._downloadFile, arg0));
            return from_candid_record_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCustomTemplate(arg0: CustomTemplate): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCustomTemplate(to_candid_CustomTemplate_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCustomTemplate(to_candid_CustomTemplate_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_CustomTemplate_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CustomTemplate): CustomTemplate {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_PrebuiltTemplate_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PrebuiltTemplate): PrebuiltTemplate {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_TemplateCategory_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TemplateCategory): TemplateCategory {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customTemplates: Array<_CustomTemplate>;
    prebuiltTemplates: Array<_PrebuiltTemplate>;
}): {
    customTemplates: Array<CustomTemplate>;
    prebuiltTemplates: Array<PrebuiltTemplate>;
} {
    return {
        customTemplates: from_candid_vec_n1(_uploadFile, _downloadFile, value.customTemplates),
        prebuiltTemplates: from_candid_vec_n6(_uploadFile, _downloadFile, value.prebuiltTemplates)
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    created: _Time;
    name: string;
    canvasState: string;
    category: _TemplateCategory;
}): {
    id: string;
    created: Time;
    name: string;
    canvasState: string;
    category: TemplateCategory;
} {
    return {
        id: value.id,
        created: value.created,
        name: value.name,
        canvasState: value.canvasState,
        category: from_candid_TemplateCategory_n4(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    name: string;
    description: string;
    thumbnailHint: string;
    category: _TemplateCategory;
}): {
    id: string;
    name: string;
    description: string;
    thumbnailHint: string;
    category: TemplateCategory;
} {
    return {
        id: value.id,
        name: value.name,
        description: value.description,
        thumbnailHint: value.thumbnailHint,
        category: from_candid_TemplateCategory_n4(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    instagram: null;
} | {
    old_money: null;
}): TemplateCategory {
    return "instagram" in value ? TemplateCategory.instagram : "old_money" in value ? TemplateCategory.old_money : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CustomTemplate>): Array<CustomTemplate> {
    return value.map((x)=>from_candid_CustomTemplate_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PrebuiltTemplate>): Array<PrebuiltTemplate> {
    return value.map((x)=>from_candid_PrebuiltTemplate_n7(_uploadFile, _downloadFile, x));
}
function to_candid_CustomTemplate_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CustomTemplate): _CustomTemplate {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid_TemplateCategory_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TemplateCategory): _TemplateCategory {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    created: Time;
    name: string;
    canvasState: string;
    category: TemplateCategory;
}): {
    id: string;
    created: _Time;
    name: string;
    canvasState: string;
    category: _TemplateCategory;
} {
    return {
        id: value.id,
        created: value.created,
        name: value.name,
        canvasState: value.canvasState,
        category: to_candid_TemplateCategory_n9(_uploadFile, _downloadFile, value.category)
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TemplateCategory): {
    instagram: null;
} | {
    old_money: null;
} {
    return value == TemplateCategory.instagram ? {
        instagram: null
    } : value == TemplateCategory.old_money ? {
        old_money: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
